## Variables, constant and placeholder
We are going to create a variable, a constant and a placeholder containing a 2X2 identyty matrix.

In [1]:
import tensorflow as tf
import numpy as np

a_const = tf.constant([[1,0],[0,1]], name="a_const")
a_variable = tf.Variable([[1,0],[0,1]],trainable=False, name="a_var")
a_placeholder = tf.placeholder(tf.int64,shape=(2,2), name="a_placeholder")
with tf.variable_scope('my_first_scope') as scope:
    a_scoped_variable = tf.Variable([[1,0],[0,1]],trainable=False, name="a_var")

print(a_const)
print(a_variable)
print(a_placeholder)
print(a_scoped_variable)

Tensor("a_const:0", shape=(2, 2), dtype=int32)
<tf.Variable 'a_var:0' shape=(2, 2) dtype=int32_ref>
Tensor("a_placeholder:0", shape=(2, 2), dtype=int64)
<tf.Variable 'my_first_scope/a_var:0' shape=(2, 2) dtype=int32_ref>


Let's now try to evaluate them inside a session:
### Constant

In [2]:
with tf.Session() as sess:
    a_value = sess.run(a_const)
    print(a_value)

[[1 0]
 [0 1]]


### Variable

In [3]:
with tf.Session() as sess:
    a_value = sess.run(a_variable)

FailedPreconditionError: Attempting to use uninitialized value a_var
	 [[Node: _retval_a_var_0_0 = _Retval[T=DT_INT32, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"](a_var)]]

Initialization is missing!!!! 
Proper way:

In [4]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    a_value = sess.run(a_variable)
    print(a_value)
    a_value = sess.run(a_scoped_variable)
    print(a_value)

[[1 0]
 [0 1]]
[[1 0]
 [0 1]]


### Placeholder

In [5]:
with tf.Session() as sess:
    a_value = sess.run(a_placeholder, feed_dict={a_placeholder:[[1,0],[0,1]]})
    print(a_value)

[[1 0]
 [0 1]]
